# Generated by Django 5.0.6 on 2024-09-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_unique_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
