# Generated by Django 5.0.3 on 2024-05-16 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ManyToManyField(related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
