# Generated by Django 5.0.3 on 2024-05-16 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_color_remove_wishlist_user_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
