# Generated by Django 5.0.3 on 2024-05-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_users_wishlist_delete_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='price',
            new_name='amount',
        ),
    ]
