# Generated by Django 5.0.3 on 2024-05-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_price_bids_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='current_bid',
            new_name='highest_bid',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='initial_bid',
            new_name='starting_price',
        ),
        migrations.AlterField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
        ),
    ]
