# Generated by Django 5.0.3 on 2024-05-21 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_current_bid_listings_highest_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='users_wishlist',
        ),
        migrations.AddField(
            model_name='listings',
            name='users_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
