# Generated by Django 5.0.3 on 2024-05-23 04:35

from django.db import migrations

def convert_color_to_hex(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')

    for category in Category.objects.all():
        category.color = "#{:06x}".format(int(category.color)).upper()
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_color'),
    ]

    operations = [
        migrations.RunPython(convert_color_to_hex)
    ]
