# Generated by Django 5.0.6 on 2024-10-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0002_alter_user_bio_alter_user_profile_image_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyapp.world'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyapp.world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='storyapp.character'),
        ),
        migrations.AlterField(
            model_name='world',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='storyapp.location'),
        ),
        migrations.AlterField(
            model_name='world',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL),
        ),
    ]
