# Generated by Django 5.0.6 on 2024-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0006_world_world_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='objectives',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
