# Generated by Django 5.0.6 on 2024-12-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0007_alter_scene_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
